# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/bluebook
        name:
        username: postgres
        password: admpostgres
    jpa:
        database-platform: co.tmunited.bluebook.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes: localhost:9300
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: true

liquibase:
    contexts: prod

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    changeLog: master-prod.xml
    fileStorage:
        env: prod
        type: remote #fileSystem or remote
        fileNameSeparator: "_"
        fileNameExtension: ".pdf"
        remote:
            basePath: http://10.1.10.141:8082
            userName: system
            userAuthorities: ROLE_SYSTEM,ROLE_USER
            urlCheckToken: /system/check-token
            tokenValidityInSeconds: 300000
            urlFiles: /system/file-stores
            urlGetFile: /system/file-stores-by-uuid
            urlGetFax: /fax/pdf-download
        fileSystem:
            processedResult: /tmp/processedResults/
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        ehcache:
            maxBytesLocalHeap: 256M
    security:
        authentication:
            jwt:
                secret: f4a18fd5976ce87a9b2193ef8a91ed1fc8a45906
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: bluebook@localhost
        baseUrl: # keep empty to use the server's default URL
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: bluebook
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
