FROM nginx

MAINTAINER UNITED DEVELOPMENT TEAM Docker Maintainers "itudt@tmunited.com"

COPY conf.d/nginx.conf /etc/nginx/nginx.conf
COPY conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY html/custom_50x.html /usr/share/nginx/html/custom_50x.html 
